package recipes.recipes.api.domain.model.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "recipes")
public final class RecipeDTO implements Serializable {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    private String name;

    private String author;

    private String instructions;

    private long servings;

    private List<IngredientDTO> ingredients;

}
