#!/bin/bash
TARGET="/home/pi/keycloak-deploy-folder"
GIT_DIR="/home/pi/keycloak.git"
BRANCH="master"

blue="\e[0;36m"
green="\e[0;92m"
yellow="\e[1;33m"
purple="\e[35m"
reset="\e[0m"

stage() {
    echo -e "[${purple}STAGE${reset}]${green}" $1 "${reset}"
}

info() {
    echo -e "[${yellow}INFO${reset}]${blue}" $1 "${reset}"
}

while read oldrev newrev ref
do
    if [ "$ref" = "refs/heads/$BRANCH" ];
    then
        info "Deploying Recipes API to production"
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        cd /home/pi/keycloak-deploy-folder/keycloak

        stage "Build"
        docker build .

        stage "Deploy"
        docker run keycloak

        else
            info "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done
a