#!/bin/bash
TARGET="/home/pi/deploy-folder"
GIT_DIR="/home/pi/project.git"
BRANCH="master"
GRADLE="/home/pi/.sdkman/candidates/gradle/7.4.2/bin/gradle"

red="\e[0;91m"
blue="\e[0;94m"
expand_bg="\e[K"
blue_bg="\e[0;104m${expand_bg}"
green_bg="\e[0;102m${expand_bg}"
green="\e[0;92m"
yellow="\e[1;33m"
purple="\e[35m"
white="\e[0;97m"
bold="\e[1m"
uline="\e[4m"
reset="\e[0m"

stage() {
    echo -e "[${purple}INFO${reset}]${green}" $1 "${reset}"
}

info() {
    echo -e "[${yellow}INFO${reset}]${blue}" $1 "${reset}"
}

while read oldrev newrev ref
do
    # only checking out the master (or whatever branch you would like to deploy)
    if [ "$ref" = "refs/heads/$BRANCH" ];
    then
        info "Deploying ${BRANCH} branch to production..."
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        cd /home/pi/deploy-folder/recipes-api

        stage "Clean"
        $GRADLE clean

        stage "Test"
        $GRADLE test
        gradle_return_code=$?
        if [ $gradle_return_code == 1 ];
        then
            info "Test failed"
        break;
        fi

        stage "Build"
        $GRADLE bootJar

        stage "Deploy"
        cp /home/pi/deploy-folder/recipes-api/build/libs/recipes-api.jar /home/pi/server

        info "Stopping old process"
        sudo systemctl stop recipes-api-service.service

        info "Starting new process"
        sudo systemctl start recipes-api-service.service


        info  "Deploy finished"
        else
                info "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
