#!/bin/bash
TARGET="/home/pi/recipes-api-deploy-folder"
GIT_DIR="/home/pi/recipes-api.git"
BRANCH="master"
#GRADLE="/home/pi/.sdkman/candidates/gradle/7.4.2/bin/gradle"

blue="\e[0;36m"
green="\e[0;92m"
yellow="\e[1;33m"
purple="\e[35m"
reset="\e[0m"

stage() {
    echo -e "[${purple}STAGE${reset}]${green}" $1 "${reset}"
}

info() {
    echo -e "[${yellow}INFO${reset}]${blue}" $1 "${reset}"
}

while read oldrev newrev ref
do
    if [ "$ref" = "refs/heads/$BRANCH" ];
    then
        info "Deploying Recipes API to production"
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        cd /home/pi/recipes-api-deploy-folder/recipes-api

        stage "Build"
        gradle clean
        gradle_return_code=$?
        if [ $gradle_return_code == 1 ];
        then
            info "Clean failed"
            exit 1
        fi

        gradle build
        gradle_return_code=$?
        if [ $gradle_return_code == 1 ];
        then
            info "Build failed"
            exit 1
        fi

        stage "Test"
        gradle test
        gradle_return_code=$?
        if [ $gradle_return_code == 1 ];
        then
            info "Test failed"
            exit 1
        fi

        stage "Package"
        gradle bootJar
        gradle_return_code=$?
        if [ $gradle_return_code == 1 ];
        then
            info "Package failed"
            exit 1
        fi

        stage "Deploy"
        cp /home/pi/recipes-api-deploy-folder/recipes-api/build/libs/recipes-api.jar /home/pi/recipes-api-server

        info "Stopping old process"
        sudo systemctl stop recipes-api-service.service

        info "Starting new process"
        sudo systemctl start recipes-api-service.service

        gradle_return_code=$?
        if [ $gradle_return_code == 1 ];
        then
            info "Deploy failed"
            exit 1
        else
            stage "Deploy done!"
        fi
        else
            info "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done
