#!/bin/bash
TARGET="/home/pi/recipes-frontend-deploy-folder"
GIT_DIR="/home/pi/recipes-frontend.git"
BRANCH="master"

blue="\e[0;36m"
green="\e[0;92m"
yellow="\e[1;33m"
purple="\e[35m"
reset="\e[0m"

stage() {
    echo -e "[${purple}STAGE${reset}]${green}" $1 "${reset}"
}

info() {
    echo -e "[${yellow}INFO${reset}]${blue}" $1 "${reset}"
}

while read oldrev newrev ref; do
    if [ "$ref" = "refs/heads/$BRANCH" ]; then
        info "Deploying Recipes frontend to production"
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        cd /home/pi/recipes-frontend-deploy-folder/recipes-frontend

        stage "Build"
        npm install
        ng build --configuration=production

        stage "Deploy"
        info "Stopping old process"
        sudo systemctl stop recipes-frontend.service

        info "Starting new process"
        sudo systemctl start recipes-frontend.service

        stage "Deploy done!"
    else
        info "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done
